#!/bin/sh
set -e

case "$1" in
  configure)
    mkdir -p /var/log/bitwarden-rs/
    systemctl --quiet daemon-reload

    echo "Adding user bitwarden-rs and creating data directory /var/lib/bitwarden-rs ..."
    mkdir -p /var/lib/bitwarden-rs
    adduser --quiet --system --group --no-create-home --home /var/lib/bitwarden-rs \
    --gecos "bitwarden-rs user" --shell /usr/bin/nologin bitwarden-rs
    chown bitwarden-rs: /var/lib/bitwarden-rs
    chown bitwarden-rs: /var/log/bitwarden-rs/
    chmod 0750 /var/lib/bitwarden-rs

    echo ""
    echo "##########"
    echo "#"
    echo "#   Remember to configure the server via its environment-variables under /etc/bitwarden-rs/env"
    echo "#   After that, enable the server via 'systemctl enable bitwarden-rs.service'"
    echo "#   Start the server via 'systemctl start bitwarden-rs.service'"
    echo "#"
    echo "##########"
    echo ""

    exit 0
esac
